export const getAllTransaction = [{
    id: 1,
    name: "Salary Deposit",
    amount: 2600.0,
    category: "Income",
    date: "2024-01-15",
    type: "income",
},
{
    id: 2,
    name: "Grocery Store",
    amount: -85.32,
    category: "Food",
    date: "2024-01-15",
    type: "expense",
},
{
    id: 3,
    name: "Electric Bill",
    amount: -120.45,
    category: "Utilities",
    date: "2024-01-14",
    type: "expense",
},
{
    id: 4,
    name: "Coffee Shop",
    amount: -12.5,
    category: "Food",
    date: "2024-01-14",
    type: "expense",
},
{
    id: 5,
    name: "Gas Station",
    amount: -55.0,
    category: "Transportation",
    date: "2024-01-13",
    type: "expense",
},
{
    id: 6,
    name: "Freelance Project",
    amount: 800.0,
    category: "Income",
    date: "2024-01-12",
    type: "income",
},
{
    id: 7,
    name: "Restaurant",
    amount: -45.8,
    category: "Food",
    date: "2024-01-12",
    type: "expense",
},
{
    id: 8,
    name: "Online Shopping",
    amount: -129.99,
    category: "Shopping",
    date: "2024-01-11",
    type: "expense",
},
{
    id: 9,
    name: "Today Pizza",
    amount: -129.99,
    category: "Shopping",
    date: "2025-09-02",
    type: "expense",
},
]

export const getAllCategories = [
    { name: "All" },
    { name: "Food" },
    { name: "Transportation" },
    { name: "Utilities" },
    { name: "Shopping" },
    { name: "Income" },
    { name: "Entertainment" },
]
   
